name: CI

on:
  push:
    branches: [ "dev" , "master" ]
  pull_request:
    branches: [ "dev" , "master" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-24.04

    env:
      DB_HOST: 127.0.0.1
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: test_db
      DB_PORT: 3306

    services:
      mysql-service:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: requirements
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm test